### ISSUE TITLE
Hubs Cloud 2/20 Triage List

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs-cloud#102]
conference:

* [x] server access email whitelist (https://github.com/mozilla/hubs-cloud/issues/27)
* [x] ability to set verified identifier (https://github.com/mozilla/hubs-cloud/issues/27)
* [x] room descriptions for homepage (https://github.com/mozilla/hubs-cloud/issues/21)
* [x] ability to disable non-admin room creation
* [x] hubs cloud discord bot (https://github.com/mozilla/hubs-cloud/issues/26)
* [ ] auto-refresh thumbnails room setting (TBD, may have a workaround)
* [ ] video refresh button (https://github.com/mozilla/hubs/issues/2104)
* [x] scene audio settings (https://github.com/mozilla/hubs-cloud/issues/32)

edu:

* [ ] customize default display names
* [ ] disable customizing display names
* [ ] dark mode user preferences showing dark text
* [ ] custom URL for logo image
* [x] custom analytics tags
* [ ] cannot upload logo and favicon successfully

DO image:

* [ ] fix rebooting of server (https://github.com/mozilla/hubs-cloud/issues/30)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-993)
